version: "3.8"

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
    - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: mongodb://admin:qwerty@mongo:27017/

  testapp:
    container_name: testapp
    image: naimss0/testapp:1.1
    ports:
      - "5050:5050"
    environment:
      - MONGO_URL=mongodb://admin:qwerty@mongo:27017
    depends_on:
      - mongo
